'Main Flow'
@startuml
start
:read manifest into object;
while (processed all files from root?) is (no)
  if (is file content?) then (no)
    :ignore file;
  else (yes)
    if (file tracked in manifest?) then (yes)
      if (file modified?) then (no)
        :ignore file;
      else (yes)
        :update modified date;
      endif
    else (no)
      :add file and modified date to manifest;
    endif
        :update manifest;
        if (template specified in file?) then (yes)
          :read specified template;
        else (no)
          :read default template;
        endif
        :run markdown on content;
        :replace content block in template with new content;
        :determine output file name from content file name and template type;
        :write new file;
    endif
endwhile (yes)
:return list of new files;
stop
@enduml